"""
Pydantic models for easli.

Extracted from server.py during Phase B modularisation. Pure data classes
with no business logic — safe to import from anywhere.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import List, Literal, Optional

from pydantic import BaseModel, Field


# ==================== ANALYSIS RESULT MODELS ====================

class Deadline(BaseModel):
    date: str = ""
    description: str = ""
    confidence: Literal["low", "medium", "high"] = "low"


class RequiredAction(BaseModel):
    action: str = ""
    urgency: Literal["low", "medium", "high"] = "low"
    reason: str = ""


class ExtractedEntities(BaseModel):
    """Concrete data points pulled from the document — used by the Reply
    Assistant to pre-fill recipient / subject / contact fields without
    forcing the user to type them again. Every field is optional because
    the OCR may not contain the value (privacy-positive default)."""
    email: str = ""
    subject: str = ""
    reference_number: str = ""
    contact_person: str = ""
    organization: str = ""


class ReplyOption(BaseModel):
    """One actionable reply intent the user can pick. The `id` MUST be one
    of the canonical intent ids so the /generate-reply endpoint can
    interpret it consistently across languages.

    Canonical intent ids:
      • inquiry          (Nachfrage stellen)
      • extension        (Fristverlängerung erbitten)
      • confirm          (Bestätigung / Annahme)
      • objection        (Widerspruch einlegen)
      • submit_documents (Unterlagen nachreichen)
      • cancel           (Kündigung / Widerruf)
    """
    id: str = ""
    label: str = ""
    reason: str = ""
    recommended: bool = False


class AnalysisResult(BaseModel):
    source_language: str = ""
    # ISO-639-1 code of the detected source language ('de', 'en', 'fr', ...).
    # Empty string when unknown.
    source_language_code: str = ""
    target_language: str = ""
    document_type: str = ""
    sender: str = ""
    summary_translated: str = ""
    simple_explanation_translated: str = ""
    key_points: List[str] = []
    deadlines: List[Deadline] = []
    required_actions: List[RequiredAction] = []
    risk_level: Literal["green", "yellow", "red"] = "green"
    risk_reason: str = ""
    # Polite neutral reply draft, written in the SAME language as the source
    # document. Replaces the old `german_reply_draft` (kept below as alias).
    reply_draft: str = ""
    # Legacy alias kept for backward compat with older clients / DB records.
    german_reply_draft: str = ""
    reply_draft_explanation_translated: str = ""
    questions_to_ask: List[str] = []
    uncertainties: List[str] = []
    disclaimer: str = ""
    # ---- Reply Assistant (interactive intent-based replies) ----------------
    extracted_entities: ExtractedEntities = Field(default_factory=ExtractedEntities)
    reply_options: List[ReplyOption] = []
    # NEW — high-level category used for filtering & sorting in history.
    category: Literal[
        "tax",
        "insurance",
        "rent",
        "bank",
        "health",
        "government",
        "court",
        "utilities",
        "telecom",
        "work",
        "education",
        "other",
    ] = "other"
    # NEW — scam / phishing detection.
    scam_warning: bool = False
    scam_reason: str = ""

    # ─── Phase EU-1: European multilingual paperwork support ────────────────
    detected_country_code: str = ""        # ISO 3166-1 alpha-2
    detected_country_name: str = ""
    jurisdiction_confidence: Literal["", "low", "medium", "high"] = ""
    suggested_reply_language_code: str = ""
    confidence_score: float = 0.0
    safety_disclaimer: str = ""


# ==================== REQUEST / RESPONSE MODELS ====================

class PageInput(BaseModel):
    file_base64: str
    mime_type: str


class AnalyzeRequest(BaseModel):
    device_id: str
    target_language: str  # one of LANGUAGES keys
    # Idempotency key generated by the client at the moment the user taps
    # "Analyze". Required-but-tolerated: if the same key is seen twice we
    # do NOT consume usage twice, even if the analysis itself runs again.
    idempotency_key: Optional[str] = None
    # Legacy single-page payload (still supported for upload / older clients):
    file_base64: Optional[str] = None
    mime_type: Optional[str] = None
    # New multi-page payload — used by the iOS-style scanner.
    pages: Optional[List[PageInput]] = None


class AnalysisRecord(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    device_id: str
    target_language: str
    target_language_label: str
    mime_type: str
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    result: AnalysisResult
    # Additional language versions of `result`.
    translations: dict = Field(default_factory=dict)


class ChatMessage(BaseModel):
    role: Literal["user", "assistant"]
    content: str
    off_topic: bool = False
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class ChatRequest(BaseModel):
    device_id: str
    message: str
    target_language: Optional[str] = None


class TranslateRequest(BaseModel):
    device_id: str
    target_language: str  # one of LANGUAGES keys


class ChatResponse(BaseModel):
    reply: str
    off_topic: bool


class AnalysisListItem(BaseModel):
    id: str
    created_at: str
    target_language: str
    target_language_label: str
    document_type: str
    sender: str
    risk_level: str
    summary_translated: str
    category: str = "other"
    scam_warning: bool = False


# ==================== USAGE / PAYWALL MODELS ====================

class UsageRecord(BaseModel):
    """Server-side usage state per anonymous device_id.

    All counters live ONLY here on the backend — never trust local storage,
    because users can reinstall the app and reset AsyncStorage at will.
    """
    device_id: str
    free_analyses_used: int = 0
    soft_extra_analyses_used: int = 0
    single_letter_credits: int = 0
    plus_active: bool = False
    plus_current_period_start: Optional[str] = None
    plus_current_period_end: Optional[str] = None
    plus_monthly_analyses_used: int = 0
    total_chat_questions_used: int = 0
    per_document_chat_questions: dict = Field(default_factory=dict)
    consumed_idempotency_keys: List[str] = Field(default_factory=list)
    translation_count: int = 0
    translated_languages: List[str] = Field(default_factory=list)
    last_usage_reset_at: Optional[str] = None
    # ── Email-Forwarding (Phase 4) ──────────────────────────────────────────
    # 8-char URL-safe token used to address this device's personal easli
    # inbox: `letters-{inbox_token}@inbox.easli.app`. Generated on first
    # GET /api/inbox/me request and never changes afterwards (rotation is
    # a deliberate user action via DELETE /api/inbox/me). Kept on the
    # usage record because it's effectively a per-device identifier and
    # we already store all per-device state here.
    inbox_token: Optional[str] = None
    inbox_letters_received: int = 0
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    updated_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class UsageResponse(BaseModel):
    """Public-safe view of usage state (no idempotency keys leaked)."""
    device_id: str
    paywall_mode: str
    free_analyses_used: int
    free_analyses_total: int
    soft_extra_used: int
    soft_extra_total: int
    single_letter_credits: int
    plus_active: bool
    plus_period_end: Optional[str]
    plus_monthly_used: int
    plus_monthly_total: int
    total_chat_questions_used: int
    total_chat_questions_total: int
    per_document_chat_questions: dict
    translation_count: int = 0
    translated_languages: List[str] = Field(default_factory=list)


class EntitlementDecision(BaseModel):
    """What the entitlement check returned for a single /api/analyze call."""
    allowed: bool
    source: Optional[Literal['plus', 'single', 'free', 'soft']] = None
    reason: Optional[Literal['payment_required', 'test_limit_reached']] = None
    message: str = ""
    usage: UsageResponse
