# Headlines + sublines for easli App Store screenshots.
# 5 scenes × 11 UI languages = 55 screenshot variants.
#
# Languages: de, en, fr, it, es, pl, ar, tr, ru, vi, zh

# Language metadata — matches /app/frontend/src/i18n.ts LANGUAGES order
LANGS = [
    ("de", "Deutsch",    "latin",  False),  # ltr
    ("en", "English",    "latin",  False),
    ("fr", "Français",   "latin",  False),
    ("it", "Italiano",   "latin",  False),
    ("es", "Español",    "latin",  False),
    ("pl", "Polski",     "latin",  False),
    ("ar", "العربية",    "arabic", True),   # rtl
    ("tr", "Türkçe",     "latin",  False),
    ("ru", "Русский",    "latin",  False),
    ("vi", "Tiếng Việt", "latin",  False),
    ("zh", "简体中文",    "cjk",    False),
]

# Simple flag as 3 colored stripes (horizontal) or 3 vertical
# Format: (orientation 'h'/'v', colors[])
FLAGS = {
    "de": ("h", ["#000000", "#DD0000", "#FFCE00"]),
    "en": ("h", ["#00247D", "#FFFFFF", "#CF142B"]),  # simplified UK
    "fr": ("v", ["#002395", "#FFFFFF", "#ED2939"]),
    "it": ("v", ["#008C45", "#F4F5F0", "#CD212A"]),
    "es": ("h", ["#AA151B", "#F1BF00", "#AA151B"]),
    "pl": ("h", ["#FFFFFF", "#FFFFFF", "#DC143C"]),
    "ar": ("h", ["#FFFFFF", "#000000", "#007A3D"]),  # pan-Arab-ish neutral
    "tr": ("h", ["#E30A17", "#E30A17", "#E30A17"]),
    "ru": ("h", ["#FFFFFF", "#0039A6", "#D52B1E"]),
    "vi": ("h", ["#DA251D", "#DA251D", "#DA251D"]),
    "zh": ("h", ["#DE2910", "#DE2910", "#DE2910"]),
}

# Scene 1: Onboarding / Language Picker — "11 languages. Zero stress."
# Scene 2: Home                         — "Letter? Snap. Done."
# Scene 3: Scan / Camera                — "One snap. Every page."
# Scene 4: Result / AI Summary          — "Plain language. In yours."
# Scene 5: Reply / Draft                — "Reply? In two seconds."

HEADLINES = {
    1: {
        "de": "11 Sprachen.\nKein Stress.",
        "en": "11 languages.\nZero stress.",
        "fr": "11 langues.\nZéro stress.",
        "it": "11 lingue.\nZero stress.",
        "es": "11 idiomas.\nCero estrés.",
        "pl": "11 języków.\nZero stresu.",
        "ar": "11 لغة.\nبلا ضغط.",
        "tr": "11 dil.\nSıfır stres.",
        "ru": "11 языков.\nБез стресса.",
        "vi": "11 ngôn ngữ.\nKhông căng thẳng.",
        "zh": "11 种语言。\n零压力。",
    },
    2: {
        "de": "Brief?\nFoto. Fertig.",
        "en": "Letter?\nSnap. Done.",
        "fr": "Courrier ?\nPhoto. Fini.",
        "it": "Lettera?\nFoto. Fatto.",
        "es": "¿Carta?\nFoto. Listo.",
        "pl": "List?\nFoto. Gotowe.",
        "ar": "رسالة؟\nصورة. تم.",
        "tr": "Mektup?\nÇek. Tamam.",
        "ru": "Письмо?\nФото. Готово.",
        "vi": "Thư?\nChụp. Xong.",
        "zh": "信件？\n拍照。搞定。",
    },
    3: {
        "de": "Ein Foto.\nAlle Seiten.",
        "en": "One snap.\nEvery page.",
        "fr": "Une photo.\nToutes les pages.",
        "it": "Uno scatto.\nOgni pagina.",
        "es": "Una foto.\nTodas las páginas.",
        "pl": "Jedno zdjęcie.\nWszystkie strony.",
        "ar": "صورة واحدة.\nكل الصفحات.",
        "tr": "Tek çekim.\nTüm sayfalar.",
        "ru": "Один снимок.\nВсе страницы.",
        "vi": "Một ảnh.\nMọi trang.",
        "zh": "一次拍摄。\n每一页。",
    },
    4: {
        "de": "Klar erklärt.\nIn deiner Sprache.",
        "en": "Plain language.\nIn yours.",
        "fr": "Expliqué clair.\nDans votre langue.",
        "it": "Spiegato chiaro.\nNella tua lingua.",
        "es": "Explicado claro.\nEn tu idioma.",
        "pl": "Jasno wyjaśnione.\nW twoim języku.",
        "ar": "شرح واضح.\nبلغتك.",
        "tr": "Net açıklama.\nKendi dilinde.",
        "ru": "Понятно.\nНа твоём языке.",
        "vi": "Giải thích rõ.\nBằng tiếng của bạn.",
        "zh": "简明解释。\n用你的语言。",
    },
    5: {
        "de": "Antwort?\nIn zwei Sekunden.",
        "en": "Reply?\nIn two seconds.",
        "fr": "Réponse ?\nEn deux secondes.",
        "it": "Rispondi?\nIn due secondi.",
        "es": "¿Responder?\nEn dos segundos.",
        "pl": "Odpowiedź?\nW dwie sekundy.",
        "ar": "ردّ؟\nفي ثانيتين.",
        "tr": "Cevap?\nİki saniyede.",
        "ru": "Ответ?\nЗа две секунды.",
        "vi": "Trả lời?\nTrong hai giây.",
        "zh": "回复？\n两秒搞定。",
    },
}

SUBLINES = {
    1: {
        "de": "Wähl deine — easli übersetzt alles.",
        "en": "Pick yours — easli translates all.",
        "fr": "Choisissez — easli traduit tout.",
        "it": "Scegli — easli traduce tutto.",
        "es": "Elige — easli traduce todo.",
        "pl": "Wybierz — easli tłumaczy wszystko.",
        "ar": "اختر — يترجم easli كل شيء.",
        "tr": "Seç — easli her şeyi çevirir.",
        "ru": "Выбери — easli переведёт всё.",
        "vi": "Chọn đi — easli dịch mọi thứ.",
        "zh": "选一种 — easli 为你翻译。",
    },
    2: {
        "de": "Dein ganzer Papierkram.",
        "en": "All your paperwork.",
        "fr": "Tous vos papiers.",
        "it": "Tutti i tuoi documenti.",
        "es": "Todos tus papeles.",
        "pl": "Wszystkie twoje papiery.",
        "ar": "كل أوراقك.",
        "tr": "Tüm evraklarınız.",
        "ru": "Все ваши документы.",
        "vi": "Mọi giấy tờ của bạn.",
        "zh": "你所有的文件。",
    },
    3: {
        "de": "Mehrseitig. Automatisch.",
        "en": "Multi-page. Automatic.",
        "fr": "Multi-pages. Automatique.",
        "it": "Multi-pagina. Automatico.",
        "es": "Varias páginas. Automático.",
        "pl": "Wielostronicowe. Automatyczne.",
        "ar": "متعدد الصفحات. تلقائي.",
        "tr": "Çok sayfalı. Otomatik.",
        "ru": "Многостраничный. Автоматически.",
        "vi": "Nhiều trang. Tự động.",
        "zh": "多页。自动。",
    },
    4: {
        "de": "Fristen. Beträge. Nächste Schritte.",
        "en": "Deadlines. Amounts. Next steps.",
        "fr": "Délais. Montants. Étapes.",
        "it": "Scadenze. Importi. Prossimi passi.",
        "es": "Plazos. Importes. Pasos.",
        "pl": "Terminy. Kwoty. Kroki.",
        "ar": "مواعيد. مبالغ. خطوات.",
        "tr": "Süreler. Tutarlar. Adımlar.",
        "ru": "Сроки. Суммы. Шаги.",
        "vi": "Hạn. Số tiền. Bước kế.",
        "zh": "期限。金额。下一步。",
    },
    5: {
        "de": "KI-Entwurf. Du sendest.",
        "en": "AI drafts. You send.",
        "fr": "L'IA rédige. Vous envoyez.",
        "it": "L'IA scrive. Tu invii.",
        "es": "La IA redacta. Tú envías.",
        "pl": "AI pisze. Ty wysyłasz.",
        "ar": "يكتب الذكاء. ترسل أنت.",
        "tr": "AI yazar. Sen gönderirsin.",
        "ru": "ИИ пишет. Ты шлёшь.",
        "vi": "AI soạn. Bạn gửi.",
        "zh": "AI 起草。你发送。",
    },
}

# Mock UI strings inside the phone for each scene + language
# Scene 1: Title + 4 visible language rows (we show flags + names from LANGS)
# Scene 2: CTA button + "Recent" label + 2 recent items
# Scene 3: "Detecting page..." + page indicator
# Scene 4: Doc title + 3 bullet summary lines + deadline label
# Scene 5: "Draft" + 3 intent chips + 2 lines of draft text

MOCK_UI = {
    1: {  # language picker
        "de": {"title": "Sprache wählen", "sub": "easli erklärt alles in dieser Sprache.", "cta": "Weiter"},
        "en": {"title": "Choose your language", "sub": "easli will explain letters in this language.", "cta": "Next"},
        "fr": {"title": "Choisir la langue", "sub": "easli expliquera les lettres dans cette langue.", "cta": "Suivant"},
        "it": {"title": "Scegli la lingua", "sub": "easli spiegherà le lettere in questa lingua.", "cta": "Avanti"},
        "es": {"title": "Elige tu idioma", "sub": "easli explicará las cartas en este idioma.", "cta": "Siguiente"},
        "pl": {"title": "Wybierz język", "sub": "easli wyjaśni listy w tym języku.", "cta": "Dalej"},
        "ar": {"title": "اختر لغتك", "sub": "سيشرح easli الرسائل بهذه اللغة.", "cta": "التالي"},
        "tr": {"title": "Dilinizi seçin", "sub": "easli mektupları bu dilde açıklayacak.", "cta": "Devam"},
        "ru": {"title": "Выберите язык", "sub": "easli объяснит письма на этом языке.", "cta": "Далее"},
        "vi": {"title": "Chọn ngôn ngữ", "sub": "easli sẽ giải thích thư bằng ngôn ngữ này.", "cta": "Tiếp"},
        "zh": {"title": "选择你的语言", "sub": "easli 将用这种语言解释信件。", "cta": "下一步"},
    },
    2: {  # home
        "de": {"title": "Willkommen", "cta": "Brief scannen", "recent": "Zuletzt", "item1": "Finanzamt · Steuerbescheid", "item2": "Krankenkasse · Rechnung", "ago1": "vor 2 Std.", "ago2": "gestern"},
        "en": {"title": "Welcome", "cta": "Scan a letter", "recent": "Recent", "item1": "Tax office · Assessment", "item2": "Health insurer · Invoice", "ago1": "2h ago", "ago2": "yesterday"},
        "fr": {"title": "Bienvenue", "cta": "Scanner un courrier", "recent": "Récent", "item1": "Impôts · Avis", "item2": "Assurance · Facture", "ago1": "il y a 2h", "ago2": "hier"},
        "it": {"title": "Benvenuto", "cta": "Scansiona lettera", "recent": "Recenti", "item1": "Agenzia Entrate · Avviso", "item2": "Assicurazione · Fattura", "ago1": "2 ore fa", "ago2": "ieri"},
        "es": {"title": "Bienvenido", "cta": "Escanear carta", "recent": "Recientes", "item1": "Hacienda · Notificación", "item2": "Seguro · Factura", "ago1": "hace 2h", "ago2": "ayer"},
        "pl": {"title": "Witamy", "cta": "Skanuj list", "recent": "Ostatnie", "item1": "Urząd · Decyzja", "item2": "Ubezpieczyciel · Faktura", "ago1": "2 godz. temu", "ago2": "wczoraj"},
        "ar": {"title": "مرحبا", "cta": "مسح رسالة", "recent": "الأحدث", "item1": "مصلحة الضرائب · إشعار", "item2": "التأمين · فاتورة", "ago1": "قبل ساعتين", "ago2": "أمس"},
        "tr": {"title": "Hoş geldin", "cta": "Mektup tara", "recent": "Son", "item1": "Vergi · Tebligat", "item2": "Sigorta · Fatura", "ago1": "2s önce", "ago2": "dün"},
        "ru": {"title": "Добро пожаловать", "cta": "Сканировать письмо", "recent": "Недавние", "item1": "Налоговая · Уведомление", "item2": "Страховая · Счёт", "ago1": "2 ч назад", "ago2": "вчера"},
        "vi": {"title": "Chào mừng", "cta": "Quét thư", "recent": "Gần đây", "item1": "Thuế · Thông báo", "item2": "Bảo hiểm · Hóa đơn", "ago1": "2 giờ trước", "ago2": "hôm qua"},
        "zh": {"title": "欢迎", "cta": "扫描信件", "recent": "最近", "item1": "税务局 · 通知", "item2": "保险 · 账单", "ago1": "2 小时前", "ago2": "昨天"},
    },
    3: {  # scan
        "de": {"status": "Seite erkannt", "page": "Seite 2 von 3", "hint": "Halte das Dokument ruhig", "cta": "Auslösen"},
        "en": {"status": "Page detected", "page": "Page 2 of 3", "hint": "Hold the document steady", "cta": "Capture"},
        "fr": {"status": "Page détectée", "page": "Page 2 sur 3", "hint": "Tenez le document immobile", "cta": "Capturer"},
        "it": {"status": "Pagina rilevata", "page": "Pagina 2 di 3", "hint": "Tieni fermo il documento", "cta": "Scatta"},
        "es": {"status": "Página detectada", "page": "Página 2 de 3", "hint": "Mantén el documento quieto", "cta": "Capturar"},
        "pl": {"status": "Strona wykryta", "page": "Strona 2 z 3", "hint": "Trzymaj dokument nieruchomo", "cta": "Zrób"},
        "ar": {"status": "تم اكتشاف الصفحة", "page": "الصفحة 2 من 3", "hint": "أبقِ المستند ثابتًا", "cta": "التقط"},
        "tr": {"status": "Sayfa algılandı", "page": "Sayfa 2 / 3", "hint": "Belgeyi sabit tut", "cta": "Çek"},
        "ru": {"status": "Страница найдена", "page": "Страница 2 из 3", "hint": "Держите документ неподвижно", "cta": "Снять"},
        "vi": {"status": "Đã nhận trang", "page": "Trang 2 / 3", "hint": "Giữ tài liệu cố định", "cta": "Chụp"},
        "zh": {"status": "检测到页面", "page": "第 2 / 3 页", "hint": "保持文档稳定", "cta": "拍摄"},
    },
    4: {  # result
        "de": {
            "doc": "Steuerbescheid 2025",
            "from": "Finanzamt München",
            "summary": "Zusammenfassung",
            "b1": "Du musst 1.247 € bis zum 15. März zahlen.",
            "b2": "Einspruch ist innerhalb von 4 Wochen möglich.",
            "b3": "Details zur Berechnung auf Seite 2.",
            "deadline_label": "Frist",
            "deadline": "15. März 2026",
        },
        "en": {
            "doc": "Tax Assessment 2025",
            "from": "Tax Office Munich",
            "summary": "Summary",
            "b1": "You owe €1,247 by March 15.",
            "b2": "You can object within 4 weeks.",
            "b3": "Calculation details on page 2.",
            "deadline_label": "Deadline",
            "deadline": "March 15, 2026",
        },
        "fr": {
            "doc": "Avis d'imposition 2025",
            "from": "Service des impôts",
            "summary": "Résumé",
            "b1": "Vous devez 1 247 € avant le 15 mars.",
            "b2": "Réclamation possible sous 4 semaines.",
            "b3": "Détails du calcul en page 2.",
            "deadline_label": "Échéance",
            "deadline": "15 mars 2026",
        },
        "it": {
            "doc": "Avviso fiscale 2025",
            "from": "Agenzia Entrate",
            "summary": "Sintesi",
            "b1": "Devi pagare 1.247 € entro il 15 marzo.",
            "b2": "Puoi fare ricorso entro 4 settimane.",
            "b3": "Dettagli del calcolo a pagina 2.",
            "deadline_label": "Scadenza",
            "deadline": "15 marzo 2026",
        },
        "es": {
            "doc": "Liquidación 2025",
            "from": "Agencia Tributaria",
            "summary": "Resumen",
            "b1": "Debes 1.247 € antes del 15 de marzo.",
            "b2": "Puedes recurrir en 4 semanas.",
            "b3": "Detalles del cálculo en página 2.",
            "deadline_label": "Plazo",
            "deadline": "15 de marzo 2026",
        },
        "pl": {
            "doc": "Decyzja podatkowa 2025",
            "from": "Urząd Skarbowy",
            "summary": "Podsumowanie",
            "b1": "Do zapłaty 1 247 € do 15 marca.",
            "b2": "Odwołanie w ciągu 4 tygodni.",
            "b3": "Szczegóły obliczenia na stronie 2.",
            "deadline_label": "Termin",
            "deadline": "15 marca 2026",
        },
        "ar": {
            "doc": "إشعار ضريبي 2025",
            "from": "مصلحة الضرائب",
            "summary": "ملخص",
            "b1": "عليك دفع 1,247 € قبل 15 مارس.",
            "b2": "يمكن الاعتراض خلال 4 أسابيع.",
            "b3": "تفاصيل الحساب في الصفحة 2.",
            "deadline_label": "الموعد",
            "deadline": "15 مارس 2026",
        },
        "tr": {
            "doc": "2025 Vergi Tebligatı",
            "from": "Vergi Dairesi",
            "summary": "Özet",
            "b1": "15 Mart'a kadar 1.247 € ödemelisin.",
            "b2": "4 hafta içinde itiraz edilebilir.",
            "b3": "Hesaplama ayrıntıları sayfa 2'de.",
            "deadline_label": "Son tarih",
            "deadline": "15 Mart 2026",
        },
        "ru": {
            "doc": "Налоговое уведомление 2025",
            "from": "Налоговая инспекция",
            "summary": "Итог",
            "b1": "Заплатить 1 247 € до 15 марта.",
            "b2": "Обжалование — в течение 4 недель.",
            "b3": "Расчёт подробно на стр. 2.",
            "deadline_label": "Срок",
            "deadline": "15 марта 2026",
        },
        "vi": {
            "doc": "Thông báo thuế 2025",
            "from": "Cơ quan thuế",
            "summary": "Tóm tắt",
            "b1": "Bạn nợ 1.247 € trước 15 tháng 3.",
            "b2": "Có thể khiếu nại trong 4 tuần.",
            "b3": "Chi tiết tính toán ở trang 2.",
            "deadline_label": "Hạn chót",
            "deadline": "15 tháng 3, 2026",
        },
        "zh": {
            "doc": "2025 年税务通知",
            "from": "税务局",
            "summary": "摘要",
            "b1": "3 月 15 日前须缴 1,247 €。",
            "b2": "可在 4 周内提出异议。",
            "b3": "计算详情见第 2 页。",
            "deadline_label": "期限",
            "deadline": "2026 年 3 月 15 日",
        },
    },
    5: {  # reply / draft
        "de": {
            "title": "Antwort verfassen",
            "intent": "Einspruch einlegen",
            "chip1": "Einspruch",
            "chip2": "Frist verlängern",
            "chip3": "Nachfrage",
            "to": "An",
            "to_val": "Finanzamt München",
            "subject": "Betreff",
            "subject_val": "Einspruch zum Bescheid vom 01.03.2026",
            "body1": "Sehr geehrte Damen und Herren,",
            "body2": "hiermit lege ich form- und fristgerecht Einspruch gegen Ihren Bescheid ein…",
            "cta": "In Mail öffnen",
        },
        "en": {
            "title": "Compose reply",
            "intent": "Lodge an objection",
            "chip1": "Object",
            "chip2": "Extend deadline",
            "chip3": "Follow-up",
            "to": "To",
            "to_val": "Tax Office Munich",
            "subject": "Subject",
            "subject_val": "Objection to assessment of 2026-03-01",
            "body1": "Dear Sir or Madam,",
            "body2": "I hereby lodge a formal and timely objection against your assessment…",
            "cta": "Open in Mail",
        },
        "fr": {
            "title": "Rédiger la réponse",
            "intent": "Déposer une réclamation",
            "chip1": "Réclamer",
            "chip2": "Prolonger",
            "chip3": "Relance",
            "to": "À",
            "to_val": "Service des impôts",
            "subject": "Objet",
            "subject_val": "Réclamation contre l'avis du 01/03/2026",
            "body1": "Madame, Monsieur,",
            "body2": "je forme par la présente une réclamation formelle contre votre avis…",
            "cta": "Ouvrir dans Mail",
        },
        "it": {
            "title": "Scrivi la risposta",
            "intent": "Presentare ricorso",
            "chip1": "Ricorso",
            "chip2": "Proroga",
            "chip3": "Richiesta",
            "to": "A",
            "to_val": "Agenzia Entrate",
            "subject": "Oggetto",
            "subject_val": "Ricorso contro avviso del 01/03/2026",
            "body1": "Spettabile Ufficio,",
            "body2": "con la presente presento formale ricorso contro il vostro avviso…",
            "cta": "Apri in Mail",
        },
        "es": {
            "title": "Redactar respuesta",
            "intent": "Presentar recurso",
            "chip1": "Recurso",
            "chip2": "Prórroga",
            "chip3": "Consulta",
            "to": "A",
            "to_val": "Agencia Tributaria",
            "subject": "Asunto",
            "subject_val": "Recurso contra la liquidación del 01/03/2026",
            "body1": "Estimados señores:",
            "body2": "por la presente interpongo recurso formal contra su liquidación…",
            "cta": "Abrir en Mail",
        },
        "pl": {
            "title": "Napisz odpowiedź",
            "intent": "Złożyć odwołanie",
            "chip1": "Odwołanie",
            "chip2": "Przedłużenie",
            "chip3": "Pytanie",
            "to": "Do",
            "to_val": "Urząd Skarbowy",
            "subject": "Temat",
            "subject_val": "Odwołanie od decyzji z 01.03.2026",
            "body1": "Szanowni Państwo,",
            "body2": "niniejszym składam formalne odwołanie od Państwa decyzji…",
            "cta": "Otwórz w Mail",
        },
        "ar": {
            "title": "كتابة الرد",
            "intent": "تقديم اعتراض",
            "chip1": "اعتراض",
            "chip2": "تمديد",
            "chip3": "استفسار",
            "to": "إلى",
            "to_val": "مصلحة الضرائب",
            "subject": "الموضوع",
            "subject_val": "اعتراض على الإشعار بتاريخ 01/03/2026",
            "body1": "السادة المحترمون،",
            "body2": "أتقدم بموجب هذا الخطاب باعتراض رسمي على إشعاركم…",
            "cta": "فتح في البريد",
        },
        "tr": {
            "title": "Yanıt yaz",
            "intent": "İtiraz gönder",
            "chip1": "İtiraz",
            "chip2": "Süre uzat",
            "chip3": "Takip",
            "to": "Alıcı",
            "to_val": "Vergi Dairesi",
            "subject": "Konu",
            "subject_val": "01.03.2026 tarihli tebligata itiraz",
            "body1": "Sayın Yetkili,",
            "body2": "işbu yazıyla tebligatınıza karşı süresi içinde itiraz ediyorum…",
            "cta": "Mail ile aç",
        },
        "ru": {
            "title": "Написать ответ",
            "intent": "Подать возражение",
            "chip1": "Возражение",
            "chip2": "Продление",
            "chip3": "Запрос",
            "to": "Кому",
            "to_val": "Налоговая инспекция",
            "subject": "Тема",
            "subject_val": "Возражение на уведомление от 01.03.2026",
            "body1": "Уважаемые господа,",
            "body2": "настоящим подаю возражение против вашего уведомления…",
            "cta": "Открыть в Mail",
        },
        "vi": {
            "title": "Soạn trả lời",
            "intent": "Khiếu nại",
            "chip1": "Khiếu nại",
            "chip2": "Gia hạn",
            "chip3": "Hỏi thêm",
            "to": "Đến",
            "to_val": "Cơ quan thuế",
            "subject": "Chủ đề",
            "subject_val": "Khiếu nại thông báo ngày 01/03/2026",
            "body1": "Kính gửi Quý cơ quan,",
            "body2": "tôi xin gửi khiếu nại chính thức đối với thông báo…",
            "cta": "Mở trong Mail",
        },
        "zh": {
            "title": "撰写回复",
            "intent": "提出异议",
            "chip1": "异议",
            "chip2": "延期",
            "chip3": "询问",
            "to": "收件人",
            "to_val": "税务局",
            "subject": "主题",
            "subject_val": "对 2026/03/01 通知的异议",
            "body1": "尊敬的先生/女士：",
            "body2": "本人特此正式对贵局通知提出异议……",
            "cta": "在邮件中打开",
        },
    },
}
