// API client for the KlarPost backend.

import { LanguageCode } from './i18n';

const BASE_URL = process.env.EXPO_PUBLIC_BACKEND_URL || '';

export interface Deadline {
  date: string;
  description: string;
  confidence: 'low' | 'medium' | 'high';
}

export interface RequiredAction {
  action: string;
  urgency: 'low' | 'medium' | 'high';
  reason: string;
}

export type Category =
  | 'tax'
  | 'insurance'
  | 'rent'
  | 'bank'
  | 'health'
  | 'government'
  | 'court'
  | 'utilities'
  | 'telecom'
  | 'work'
  | 'education'
  | 'other';

export interface AnalysisResult {
  source_language: string;
  target_language: string;
  document_type: string;
  sender: string;
  summary_translated: string;
  simple_explanation_translated: string;
  key_points: string[];
  deadlines: Deadline[];
  required_actions: RequiredAction[];
  risk_level: 'green' | 'yellow' | 'red';
  risk_reason: string;
  german_reply_draft: string;
  reply_draft_explanation_translated: string;
  questions_to_ask: string[];
  uncertainties: string[];
  disclaimer: string;
  category: Category;
  scam_warning: boolean;
  scam_reason: string;
}

export interface AnalysisRecord {
  id: string;
  device_id: string;
  target_language: string;
  target_language_label: string;
  mime_type: string;
  created_at: string;
  result: AnalysisResult;
}

export interface AnalysisListItem {
  id: string;
  created_at: string;
  target_language: string;
  target_language_label: string;
  document_type: string;
  sender: string;
  risk_level: 'green' | 'yellow' | 'red';
  summary_translated: string;
  category: Category;
  scam_warning: boolean;
}

export interface ChatMessage {
  role: 'user' | 'assistant';
  content: string;
  off_topic: boolean;
  created_at: string;
}

async function jsonOrThrow<T>(res: Response): Promise<T> {
  const text = await res.text();
  let body: any = null;
  try {
    body = text ? JSON.parse(text) : null;
  } catch {
    body = text;
  }
  if (!res.ok) {
    const msg = (body && body.detail) || (typeof body === 'string' ? body : `HTTP ${res.status}`);
    throw new Error(typeof msg === 'string' ? msg : JSON.stringify(msg));
  }
  return body as T;
}

export interface AnalyzePage {
  file_base64: string;
  mime_type: string;
}

// Re-export the typed errors from `usage.ts` so existing callers can keep
// importing everything from `api.ts`.
export {
  PaymentRequiredError,
  TestLimitReachedError,
  type UsageState,
} from './usage';

import {
  PaymentRequiredError,
  TestLimitReachedError,
  type UsageState,
} from './usage';

export async function analyzeDocument(params: {
  device_id: string;
  target_language: LanguageCode;
  pages: AnalyzePage[];
  /** Idempotency key generated by the client at the moment the user taps
   *  "Analyze". Same key sent twice → backend will not double-consume. */
  idempotency_key?: string;
}): Promise<AnalysisRecord & { usage?: UsageState }> {
  const res = await fetch(`${BASE_URL}/api/analyze`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(params),
  });

  // Special-case the entitlement-gate responses BEFORE the generic error
  // handler so callers can route the user to the paywall / test-limit
  // banner instead of showing a raw error toast.
  if (res.status === 402 || res.status === 429) {
    let body: any = null;
    try {
      body = await res.json();
    } catch {
      // ignore — fall through to a generic error
    }
    if (body?.usage) {
      const message: string = body.message || '';
      if (res.status === 402 || body.error === 'payment_required') {
        throw new PaymentRequiredError(message, body.usage as UsageState);
      }
      throw new TestLimitReachedError(
        message || 'Dein Testkontingent ist erreicht. Danke fürs Testen von KlarPost.',
        body.usage as UsageState,
      );
    }
  }

  return jsonOrThrow<AnalysisRecord & { usage?: UsageState }>(res);
}

export async function listAnalyses(deviceId: string): Promise<AnalysisListItem[]> {
  const res = await fetch(`${BASE_URL}/api/analyses?device_id=${encodeURIComponent(deviceId)}`);
  return jsonOrThrow<AnalysisListItem[]>(res);
}

export async function getAnalysis(id: string, deviceId: string): Promise<AnalysisRecord> {
  const res = await fetch(`${BASE_URL}/api/analyses/${encodeURIComponent(id)}?device_id=${encodeURIComponent(deviceId)}`);
  return jsonOrThrow<AnalysisRecord>(res);
}

export async function deleteAnalysis(id: string, deviceId: string): Promise<void> {
  const res = await fetch(`${BASE_URL}/api/analyses/${encodeURIComponent(id)}?device_id=${encodeURIComponent(deviceId)}`, {
    method: 'DELETE',
  });
  await jsonOrThrow(res);
}

export async function deleteAllAnalyses(deviceId: string): Promise<void> {
  // DSGVO Art. 17 — calls the explicit /api/history/{device_id} endpoint
  // which wipes both analyses AND chat messages in one shot.
  const res = await fetch(
    `${BASE_URL}/api/history/${encodeURIComponent(deviceId)}`,
    { method: 'DELETE' }
  );
  await jsonOrThrow(res);
}

export interface ExportPayload {
  app: string;
  device_id: string;
  exported_at: string;
  data_residency: string;
  count: number;
  analyses: AnalysisRecord[];
}

export async function exportMyData(deviceId: string): Promise<ExportPayload> {
  const res = await fetch(`${BASE_URL}/api/export?device_id=${encodeURIComponent(deviceId)}`);
  return jsonOrThrow<ExportPayload>(res);
}

export async function listChatMessages(analysisId: string, deviceId: string): Promise<ChatMessage[]> {
  const res = await fetch(
    `${BASE_URL}/api/analyses/${encodeURIComponent(analysisId)}/messages?device_id=${encodeURIComponent(deviceId)}`
  );
  return jsonOrThrow<ChatMessage[]>(res);
}

export async function sendChatMessage(
  analysisId: string,
  deviceId: string,
  message: string
): Promise<ChatMessage> {
  const res = await fetch(`${BASE_URL}/api/analyses/${encodeURIComponent(analysisId)}/chat`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ device_id: deviceId, message }),
  });
  return jsonOrThrow<ChatMessage>(res);
}

export async function clearChatMessages(analysisId: string, deviceId: string): Promise<void> {
  const res = await fetch(
    `${BASE_URL}/api/analyses/${encodeURIComponent(analysisId)}/messages?device_id=${encodeURIComponent(deviceId)}`,
    { method: 'DELETE' }
  );
  await jsonOrThrow(res);
}
